config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Sidekiq::Web => "/sidekiq", :constraints => AdminConstraint.new

  resources :apidocs, only: [:index]

  namespace :admin do
    resources :users do
      get :login
      patch :merge
    end
    resources :exports
    resources :data_sets
    resources :districts do
      collection do
        get :bulk
        post :bulk_update
      end
    end
    resources :notices do
      post :analyze
    end
    resources :bulk_uploads
    resources :replies
    resources :snippets
    resources :signs
    resources :plates
    resources :charges
    resources :charge_variants
    resources :authorizations
    resources :brands

    root to: "users#index"
  end

  # this is not administrate but our own
  scope "/admin" do
    get :system, to: "system#index", as: :system_status
    post :blocklist_ip, to: "system#blocklist_ip", as: :blocklist_ip
  end

  namespace :api, constraints: { format: :json } do
    resources :notices do
      member { patch :mail }
    end
    resources :uploads, only: [:create]
    resources :exports, only: [:index] do
      collection { get :public }
    end
    resources :districts, only: [:index, :show]
    resources :signs, only: [:index, :show]
    resources :plates, only: [:index, :show]
    resources :charges, only: [:index, :show]
    resources :brands, only: [:index, :show]
  end

  resources :replies
  resources :snippets
  resources :brands, except: [:delete]

  resources :bulk_uploads do
    member { patch :purge }

    collection do
      post :bulk
      post :import
    end
  end

  resources :notices do
    member do
      get :inspect
      get :share
      get :suggest
      get :suggest_address
      get :pdf
      get :winowig
      get :retrieve
      get :mergers
      patch :forward
      patch :status
      patch :duplicate
      patch :mail
      patch :enable
      patch :disable
      patch :analyze
      patch :reanalyze
      patch :purge
      patch :upload
      patch :merge
    end

    collection do
      get :stats
      get :map
      get :archived
      post :geocode
      post :bulk
      post :import
    end
  end

  resource :user, except: %i[create new index] do
    member do
      get :studi
      patch :confirmation_mail
      patch :signature
      patch :destroy_signature
    end
  end
  # https://github.com/rails/rails/issues/1769#issuecomment-301643924
  resolve("User") { [:user] }

  namespace :user do
    resources :exports, only: %i[index create destroy]
  end

  resources :districts
  resources :plates, only: %i[index show]
  resources :signs, only: %i[index] do
    member { get :show, constraints: { id: Sign::ID_REGEX } }
  end
  resources :charges, only: %i[index show] do
    collection { get :list }
  end

  resources :exports, only: :index
  resource :sitemap, only: :show

  scope "/p" do
    get "/charge/:token", to: "public#charge", as: :public_charge
    get "/profile/:token", to: "public#profile", as: :public_profile
    get "/archive/:user_token/:notice_token", to: "public#archive", as: :public_archive, defaults: { format: :zip }
  end

  scope "/auth" do
    unless Rails.env.production?
      get "/offline_login/:nickname", to: "sessions#offline_login"
    end
    post "/twitter_murks", to: "sessions#twitter_murks"
    get "/:provider/callback", to: "sessions#create", as: :provider_callback
    post "/:provider/callback", to: "sessions#create" # just for Apple
    delete "/:provider", to: "sessions#disconnect"
    get "/failure", to: "sessions#failure"
    get "/destroy_alias_session", to: "sessions#destroy_alias", as: :logout_alias
    get "/destroy_session", to: "sessions#destroy", as: :logout
    get "/validation/:token", to: "sessions#validation", as: :validation
    get "/signup", to: "sessions#signup", as: :signup
    get "/ticket", to: "sessions#ticket", as: :ticket
    get "/login", to: "sessions#login", as: :login
    get "/email", to: "sessions#email", as: :email_login
    post "/complete", to: "sessions#complete", as: :complete
  end

  scope "/sessions" do
    get "/email", to: "sessions#email"
    post "/email_signup", to: "sessions#email_signup", as: :email_signup
  end

  root "home#index"

  get "/home", to: "home#index", as: :home
  get "/wegeheld", to: "home#wegeheld", as: :wegeheld
  get "/generator", to: "home#generator", as: :generator
  get "/imprint", to: "home#imprint", as: :imprint
  get "/map", to: "home#map", as: :map
  get "/leaderboard", to: "home#leaderboard", as: :leaderboard
  get "/stats", to: "home#stats", as: :stats
  get "/features", to: "home#features", as: :features
  get "/integrations", to: "home#integrations", as: :integrations
  get "/faq", to: "home#faq", as: :faq
  get "/api", to: "home#api", as: :api
  get "/violation", to: "home#violation", as: :violation
  get "/privacy", to: "home#privacy", as: :privacy
  get "/donate", to: "home#donate", as: :donate
  get "/year", to: "home#year", as: :year
  get "/robots", to: "home#robots", defaults: { format: :txt }, as: :robots
  get "/year2022" => redirect("/year?year=2022")
  get "/year2021" => redirect("/year?year=2021")
  get "/year2020" => redirect("/year?year=2020")
  get "/year2019" => redirect("/year?year=2019")

  if Rails.env.development?
    get "/cdn-cgi/image/width=:width,height=:height,fit=:fit,quality=:quality/storage/:key.:extension", to: "styleguide#photo"
  end

  get "/styleguide", to: "styleguide#index"

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  get "/ping", to: ->(env) { [200, { "Content-Type" => "text/html" }, ["pong"]] }
  match '*path.php', via: :all, to: ->(_env) { [302, { 'Location' => 'https://www.weg.li/violation/' }, ['Scheiße geparkt? Parkt nicht auf unseren Wegen!']] }
end

app/models/api/plate.rb
# frozen_string_literal: true

class Api::Plate < Plate
  include Swagger::Blocks

  swagger_schema :Plate do
    property :name do
      key :type, :string
    end
    property :prefix do
      key :type, :string
    end
    property :zips do
      key :type, :array
      items do
        key :type, :string
      end
    end
  end
end

app/models/plate.rb
# frozen_string_literal: true

class Plate < ApplicationRecord
  acts_as_api

  api_accessible :public_beta do |template|
    %i[
      name
      prefix
      zips
      created_at
      updated_at
    ].each { |key| template.add(key) }
  end

  validates :name, presence: true
  validates :prefix, presence: true, uniqueness: true

  scope :ordered, -> { order(:name) }
  scope :search, ->(term) { where("name ILIKE :term OR prefix ILIKE :term", term: "%#{term}%") }

  def self.from_param(param)
    param = param.split("-").first || param
    find_by!(prefix: param)
  end

  def to_param
    "#{prefix}-#{name.parameterize}"
  end
end

app/controllers/admin/plates_controller.rb
module Admin
  class PlatesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/plates_controller.rb
# frozen_string_literal: true

class Api::PlatesController < Api::ApplicationController
  swagger_path "/Plates" do
    operation :get do
      key :summary, "Get all Plates"
      key :description, "Returns a list of all Plates"
      key :tags, ["Plate"]
      response 200 do
        key :description, "Plate response"
        schema do
          key :type, :array
          items { key :$ref, :Plate }
        end
      end
      response :default do
        key :description, "unexpected error"
        schema { key :$ref, :Error }
      end
    end
  end

  def index
    render json: Plate.ordered.as_api_response(:public_beta)
  end

  swagger_path "/Plates/{number}" do
    operation :get do
      key :summary, "Get Plate"
      key :description, "Gets a Plate for given number/id"
      key :tags, ["Plate"]
      parameter do
        key :name, :number
        key :in, :path
        key :description, "Number of Plate"
        key :required, true
        key :type, :string
      end
      response 200 do
        key :description, "Plate response"
        schema { key :$ref, :Plate }
      end
      response :default do
        key :description, "unexpected error"
        schema { key :$ref, :Error }
      end
    end
  end

  def show
    render json: Plate.ordered.from_param(params[:number] || params[:id]).as_api_response(:public_beta)
  end
end

app/controllers/plates_controller.rb
# frozen_string_literal: true

class PlatesController < ApplicationController
  def index
    respond_to do |format|
      format.html { @plates = search_scope }
      format.csv do
        csv_data = CSV.generate(force_quotes: true) do |csv|
          csv << %w[Name Ortskennzeichen]
          Plate.ordered.pluck(:name, :prefix).each { |plate| csv << plate }
        end
        send_data(csv_data, type: "text/csv; charset=UTF-8; header=present", disposition: "attachment; filename=plate-#{Time.now.to_i}.csv")
      end
    end
  end

  def show
    @plate = Plate.from_param(params[:id])
    respond_to do |format|
      format.html do
        @districts = District.where(zip: @plate.zips).pluck(:name, :zip).group_by { |name, _zip| name }
        render :show
      end
      format.json { render json: @plate.as_api_response(:public_beta) }
    end
  end

  private

  def search_scope
    plate = Plate.order(params[:order] || "name ASC").page(params[:page])
    if params[:term].present?
      plate = plate.search(params[:term])
    end
    plate
  end
end

app/views/plates/_header.html.slim
.page-header
  = link_to signs_path, title: 'Ortskennzeichen' do
    h2.text-primary weg.li Ortskennzeichen

app/views/plates/index.html.slim
- set_title t('navigation.plates')
- set_meta_description t('meta_description.plates')

.well
  |
    Bei weg.li sind derzeit #{number_with_delimiter(Plate.count)} Ortskennzeichen hinterlegt.

.panel.panel-default
  .panel-heading
    .row
      .col-xs-8
      .col-xs-4.text-right
        button.btn.btn-default.btn-sm.dropdown-toggle type="button" data-toggle="dropdown"
          | <span class="glyphicon glyphicon-search"></span> Suche <span class="caret"></span>
        ul.dropdown-menu.dropdown-menu-right
          li
            = form_tag({url: url_for}, method: :get, class: 'form-dropdown', autocomplete: :off) do
              .input-group.input-group-sm
                = text_field_tag(:term, params[:term], placeholder: 'z.B. HH', class: 'form-control input-sm', autofocus: true)
                span.input-group-btn
                  = button_tag(class: "btn btn-default btn-sm")
                    span.glyphicon.glyphicon-search

          - if params[:term].present?
            li.divider
            li
              = link_to url_for
                span.glyphicon.glyphicon-remove>
                | ohne Suche

  .table-responsive
    table.table.table-striped.table-hover
      thead
        tr
          th
          th = Plate.human_attribute_name(:name)
          th = Plate.human_attribute_name(:prefix)
          th Postleitzahlen
      tbody
        - if @plates.present?
          - @plates.each do |plate|
            tr
              td
              td = link_to(registration_label("#{plate.prefix}-XYZ 123"), plate)
              td = link_to(plate.name, plate)
              td = link_to(plate.zips.join(', ').truncate(22), plate)
        - else
          tr
            td(colspan=4) Es wurden keine Einträge gefunden.

.text-center
  = paginate @plates

app/views/plates/show.html.slim
- set_title [t('navigation.plates'), @plate.name, @plate.prefix].join(' ')
- set_canonical plate_url(@plate, host: Rails.application.config.default_host)
- set_meta_description t('meta_description.plate', name: @plate.name, prefix: @plate.prefix)

h3 #{@plate.name} #{@plate.prefix}

.spacer

.row
  .col-lg-6
    - @districts.each do |name, group|
      .panel.panel-default
        .panel-heading= name
        ul.list-group
          - group.each do |name, zip|
            li.list-group-item
              => registration_label("#{@plate.prefix}-XYZ 123")
              = link_to "#{zip} #{name}", district_path(zip), title: name

  - if @plate.zips.present?
    .col-lg-6
      .panel.panel-default
        .panel-heading Postleitzahlen
        ul.list-group
          li.list-group-item
            = @plate.zips.join(', ')