config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Sidekiq::Web => "/sidekiq", :constraints => AdminConstraint.new

  resources :apidocs, only: [:index]

  namespace :admin do
    resources :users do
      get :login
      patch :merge
    end
    resources :exports
    resources :data_sets
    resources :districts do
      collection do
        get :bulk
        post :bulk_update
      end
    end
    resources :notices do
      post :analyze
    end
    resources :bulk_uploads
    resources :replies
    resources :snippets
    resources :signs
    resources :plates
    resources :charges
    resources :charge_variants
    resources :authorizations
    resources :brands

    root to: "users#index"
  end

  # this is not administrate but our own
  scope "/admin" do
    get :system, to: "system#index", as: :system_status
    post :blocklist_ip, to: "system#blocklist_ip", as: :blocklist_ip
  end

  namespace :api, constraints: { format: :json } do
    resources :notices do
      member { patch :mail }
    end
    resources :uploads, only: [:create]
    resources :exports, only: [:index] do
      collection { get :public }
    end
    resources :districts, only: [:index, :show]
    resources :signs, only: [:index, :show]
    resources :plates, only: [:index, :show]
    resources :charges, only: [:index, :show]
    resources :brands, only: [:index, :show]
  end

  resources :replies
  resources :snippets
  resources :brands, except: [:delete]

  resources :bulk_uploads do
    member { patch :purge }

    collection do
      post :bulk
      post :import
    end
  end

  resources :notices do
    member do
      get :inspect
      get :share
      get :suggest
      get :suggest_address
      get :pdf
      get :winowig
      get :retrieve
      get :mergers
      patch :forward
      patch :status
      patch :duplicate
      patch :mail
      patch :enable
      patch :disable
      patch :analyze
      patch :reanalyze
      patch :purge
      patch :upload
      patch :merge
    end

    collection do
      get :stats
      get :map
      get :archived
      post :geocode
      post :bulk
      post :import
    end
  end

  resource :user, except: %i[create new index] do
    member do
      get :studi
      patch :confirmation_mail
      patch :signature
      patch :destroy_signature
    end
  end
  # https://github.com/rails/rails/issues/1769#issuecomment-301643924
  resolve("User") { [:user] }

  namespace :user do
    resources :exports, only: %i[index create destroy]
  end

  resources :districts
  resources :plates, only: %i[index show]
  resources :signs, only: %i[index] do
    member { get :show, constraints: { id: Sign::ID_REGEX } }
  end
  resources :charges, only: %i[index show] do
    collection { get :list }
  end

  resources :exports, only: :index
  resource :sitemap, only: :show

  scope "/p" do
    get "/charge/:token", to: "public#charge", as: :public_charge
    get "/profile/:token", to: "public#profile", as: :public_profile
    get "/archive/:user_token/:notice_token", to: "public#archive", as: :public_archive, defaults: { format: :zip }
  end

  scope "/auth" do
    unless Rails.env.production?
      get "/offline_login/:nickname", to: "sessions#offline_login"
    end
    post "/twitter_murks", to: "sessions#twitter_murks"
    get "/:provider/callback", to: "sessions#create", as: :provider_callback
    post "/:provider/callback", to: "sessions#create" # just for Apple
    delete "/:provider", to: "sessions#disconnect"
    get "/failure", to: "sessions#failure"
    get "/destroy_alias_session", to: "sessions#destroy_alias", as: :logout_alias
    get "/destroy_session", to: "sessions#destroy", as: :logout
    get "/validation/:token", to: "sessions#validation", as: :validation
    get "/signup", to: "sessions#signup", as: :signup
    get "/ticket", to: "sessions#ticket", as: :ticket
    get "/login", to: "sessions#login", as: :login
    get "/email", to: "sessions#email", as: :email_login
    post "/complete", to: "sessions#complete", as: :complete
  end

  scope "/sessions" do
    get "/email", to: "sessions#email"
    post "/email_signup", to: "sessions#email_signup", as: :email_signup
  end

  root "home#index"

  get "/home", to: "home#index", as: :home
  get "/wegeheld", to: "home#wegeheld", as: :wegeheld
  get "/generator", to: "home#generator", as: :generator
  get "/imprint", to: "home#imprint", as: :imprint
  get "/map", to: "home#map", as: :map
  get "/leaderboard", to: "home#leaderboard", as: :leaderboard
  get "/stats", to: "home#stats", as: :stats
  get "/features", to: "home#features", as: :features
  get "/integrations", to: "home#integrations", as: :integrations
  get "/faq", to: "home#faq", as: :faq
  get "/api", to: "home#api", as: :api
  get "/violation", to: "home#violation", as: :violation
  get "/privacy", to: "home#privacy", as: :privacy
  get "/donate", to: "home#donate", as: :donate
  get "/year", to: "home#year", as: :year
  get "/robots", to: "home#robots", defaults: { format: :txt }, as: :robots
  get "/year2022" => redirect("/year?year=2022")
  get "/year2021" => redirect("/year?year=2021")
  get "/year2020" => redirect("/year?year=2020")
  get "/year2019" => redirect("/year?year=2019")

  if Rails.env.development?
    get "/cdn-cgi/image/width=:width,height=:height,fit=:fit,quality=:quality/storage/:key.:extension", to: "styleguide#photo"
  end

  get "/styleguide", to: "styleguide#index"

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  get "/ping", to: ->(env) { [200, { "Content-Type" => "text/html" }, ["pong"]] }
  match '*path.php', via: :all, to: ->(_env) { [302, { 'Location' => 'https://www.weg.li/violation/' }, ['Scheiße geparkt? Parkt nicht auf unseren Wegen!']] }
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  helper_method :goals, :statistics, :yearly_statistics, :count_sum

  def index; end

  def robots
    @disallow = request.subdomain == "images"
  end

  def map
    @limit = (params[:limit] || 5).to_i
    @since = (params[:since] || "7").to_i
    @display = params[:display] || "cluster"

    @district = params[:district] || current_user&.city
    @default_district =
      District.active.find_by(name: @district) ||
      District.active.find_by(name: "Hamburg") || District.active.first
    @district = @default_district.name

    @notices =
      Notice
        .includes(:user)
        .shared
        .since(@since.days.ago)
        .joins(:district)
        .where(districts: { name: @default_district.name })
    @active = @notices.map(&:user_id).uniq.size
  end

  def stats
    @since = (params[:since] || 4).to_i
    @display = params[:display] || "user"
    @interval = params[:interval] || "1 week"
  end

  def year
    @limit = (params[:limit] || 5).to_i
    @years = years
    @year = @years.include?(params[:year].to_i) ? params[:year].to_i : @years.max
  end

  def leaderboard
    @limit = (params[:limit] || 5).to_i
  end

  helper_method :weekly_leaders, :monthly_leaders, :yearly_leaders, :total_leaders, :year_leaders, :leaderboard_users

  def year_leaders
    @year_leaders = years[1..].to_h { |year| [year, leaders_count(year, @limit)] }
  end

  def leaderboard_users
    @leaderboard_users ||= begin
      user_ids = weekly_leaders.keys + monthly_leaders.keys + yearly_leaders.keys + total_leaders.keys + year_leaders.values.flat_map(&:keys)
      User.find(user_ids)
    end
  end

  def weekly_leaders
    @weekly_leaders ||= leaders(Time.zone.now.beginning_of_week, @limit)
  end

  def monthly_leaders
    @monthly_leaders ||= leaders(Time.zone.now.beginning_of_month, @limit)
  end

  def yearly_leaders
    @yearly_leaders ||= leaders(Time.zone.now.beginning_of_year, @limit)
  end

  def total_leaders
    @total_leaders ||= leaders(10.years.ago, @limit)
  end

  def generator
    if params[:stadtreinigung].present?
      data = ParkGenerator.new.generate(params[:stadtreinigung_name])

      send_data data, filename: "Stadtreinigung #{params[:stadtreinigung_name]}.pdf"
    elsif params[:parkraummanagement].present?
      data = ViolationGenerator.new.generate(params[:parkraummanagement_name])

      send_data data, filename: "Parkraum-Management #{params[:parkraummanagement_name]}.pdf"
    end
  end

  private

  def years
    (2019..Time.zone.now.year).to_a.reverse
  end

  def leaders(since, limit)
    Notice
      .shared
      .since(since)
      .group(:user_id)
      .order(count_all: :desc)
      .limit(limit)
      .count
  end

  def leaders_count(year, limit)
    Notice.where(start_date: ("01.01.#{year}".to_date.beginning_of_year)..("31.12.#{year}".to_date.end_of_year))
      .shared
      .group(:user_id)
      .order(count_all: :desc)
      .limit(limit)
      .count
  end

  def count_sum
    @count_sum ||=
      case @display
      when "user"
        {
          counts:
            User.count_over(User.active, weeks: @since, interval: @interval),
          sums: User.sum_over(User.active, weeks: @since, interval: @interval),
        }
      when "active"
        {
          counts:
            User.count_over(
              User.active.joins(:notices),
              weeks: @since,
              interval: @interval,
            ),
          sums:
            User.sum_over(
              User.active.joins(:notices),
              weeks: @since,
              interval: @interval,
            ),
        }
      when "notice"
        {
          counts:
            Notice.count_over(
              Notice.shared,
              weeks: @since,
              interval: @interval,
            ),
          sums:
            Notice.sum_over(Notice.shared, weeks: @since, interval: @interval),
        }
      when "photo"
        {
          counts:
            Notice.count_over(
              ActiveStorage::Attachment.where(
                record_type: "Notice",
                name: "photos",
              ),
              weeks: @since,
              interval: @interval,
            ),
          sums:
            Notice.sum_over(
              ActiveStorage::Attachment.where(
                record_type: "Notice",
                name: "photos",
              ),
              weeks: @since,
              interval: @interval,
            ),
        }
      else
        { counts: {}, sums: {} }
      end
  end

  def yearly_statistics
    @yearly_statistics ||= Notice.yearly_statistics(@year, @limit)
  end

  def goals
    @goals ||= {
      week: Notice.shared.since(Time.zone.now.beginning_of_week).count,
      month: Notice.shared.since(Time.zone.now.beginning_of_month).count,
      year: Notice.shared.since(Time.zone.now.beginning_of_year).count,
    }
  end

  def statistics
    @statistics ||= Notice.statistics
  end
end

app/views/home/_tips_teaser.html.slim
.row
  .col-lg-2.text-center
    = image_tag 'phoet.jpg', class: "img-circle me-quote"
  .col-lg-10
    blockquote
      p Es gibt viele tolle Projekte rund um die Themen Verkehr und Mobilität, hier ein paar interessante Tipps:
      small Peter aus Friedland, 👨‍👦 besorgter Vater, 🚶‍♂️ Fußgänger, 🛴 E-Scooterer, 🚲 Radler und 🚐 Autofahrer

app/views/home/_year2019.slim
.alert.alert-success
  dl.dl-horizontal
    dt 1. August 2019
    dd weg.li startet in die <a href="https://docs.google.com/document/d/1SQTXXvGY8BzL-NgjXAKm0EVZ3YTqHOMPonWtVJk7vxg/edit" target="_blank">Beta-Phase</a> für den <strong>Bezirk Hamburg</strong> 📸
    dt 11. August 2019
    dd die Tester erreichen das <strong>1. Wochenziel</strong> von <strong>100 Anzeigen</strong> 🥰
    dt 20. August 2019
    dd die <strong>ersten 💯</strong> Tester haben sich registriert 🚀
    dt 22. September 2019
    dd weg.li erreicht durchweg mehr als 100 Meldungen und erhöht das Wochenziel auf <strong>500 Anzeigen</strong> 💪

app/views/home/_year2020.slim
.alert.alert-success
  dl.dl-horizontal
    dt 1. Januar 2020
    dd weg.li erreicht durchweg mehr als 500 Meldungen und erhöht das Wochenziel auf <strong>1.000 Anzeigen</strong> 💪
    dt 22. Januar 2020
    dd weg.li hilft auch offline, Anzeigen kann man nun <a href="https://twitter.com/weg_li/status/1219640084980535296" target="_blank">als PDF Herunterladen</a> 📃
    dt 1. Februar 2020
    dd wer möchte, der kann weg.li auch als #{link_to 'Github Sponsor', 'https://github.com/sponsors/phoet/'} unterstützen 💖
    dt 14. Februar 2020
    dd das weg.li #{link_to 'Leaderboard', leaderboard_path} geht live 🚀
    dt 17. Februar 2020
    dd Beweisfotos können per Google-Photos importiert werden 🌆
    dt 24. Februar 2020
    dd weg.li erreicht durchweg mehr als 1.000 Meldungen und erhöht das Wochenziel auf <strong>2.000 Anzeigen</strong> ✊
    dt 29. Februar 2020
    dd Häufig genutzte Hinweise können als Vorlagen hinterlegt werden 📝

app/views/home/_year2024.slim
.alert.alert-success
  dl.dl-horizontal
    dt 1. Januar 2024
    dd weg.li wünscht allen Falschparker-Meldern einen fröhlichen und gesunden Start in das neue Jahr 🎇
    dt 6. Januar 2024
    dd die #{link_to 'Fahrzeugmarken', brands_path} können nun, ebenso wie bereits Bezirke, von der Community gepflegt werden 🚗
    dt 26. Februar 2024
    dd der Anzeigenhauptmeister geht viral durch #{link_to 'einen Beitrag von Spiegel-Panorama', 'https://www.spiegel.de/panorama/gesellschaft/kein-pardon-fuer-parksuender-ich-bin-der-anzeigenhauptmeister-spiegel-tv-a-cae5d191-afe5-4284-95ec-6772fb7bb4a1', target: :blank} 🦠
    dt 25. April 2024
    dd das Wochenziel wird auf 8.000 Anzeigen angehoben 😎
    dt 25. Oktober 2024
    dd Gismofighter meldet #{link_to 'Parkverstoß Nr. 1.000.000', 'https://bsky.app/profile/weg.li/post/3lbk5vy4pic27', target: :blank} 🎉
    dt 23. November 2024
    dd Socialmedia ist jetzt #{link_to '@weg.li bei Bluesky', 'https://bsky.app/profile/weg.li', target: :blank} 🦋
    dt 16. Dezember 2024
    dd Die neue, vollintegrierte WiNOWiG Integration mit Dresden geht live! 🚀

app/views/home/_year2026.slim
.alert.alert-success
  dl.dl-horizontal
    dt 1. Januar 2026
    dd weg.li wünscht allen Falschparker-Meldern einen fröhlichen und gesunden Start in das neue Jahr 🎇
    dt 3. Februar 2026
    dd Die Analyse der Beweisfotos durch KI-Modelle Gemini Flash hat begonnen. Wir sind gespannt auf die Ergebnisse und hoffen, dass sie dazu beitragen werden, die Straßen sicherer zu machen 🚗💨

app/views/home/_year_head.slim
.row
  .col-lg-2.text-center
    = image_tag 'phoet.jpg', class: "img-circle me-quote"
  .col-lg-10
    blockquote
      p In #{year} wurden bereits #{number_with_delimiter(users_count)} Anzeigen von #{number_with_delimiter(users_active)} Benutzern erstattet - vielen Dank!
      small = "weg.li 🚲💨 #{t('slogan_1')} #{t('slogan_2')} #{t('slogan_3')}"

app/views/home/donate.html.slim
.page-header
  h2.text-primary Spenden für weg.li

.spacer

.row
  .col-lg-2.text-center
    = image_tag 'phoet.jpg', class: 'img-circle me-quote'
  .col-lg-10
    blockquote
      p Mit Deiner Spende unterstützt Du uns dabei weg.li überhaupt möglich zu machen - vielen Dank 🥰
      small = "weg.li 🚲💨 #{t('slogan_1')} #{t('slogan_2')}"

.spacer-large

.well.well-sm.callout-success
  .row
    .col-lg-6.text-center
      h4
        <span class="glyphicon glyphicon-piggy-bank"></span> Spenden per Überweisung

      p
        small.text-muted
          |
            Da weg.li nicht als gemeinnützig anerkannt ist, können keine steuerlich absetzbaren Spendenquittungen ausgestellt werden!

    .col-lg-6.text-center
      dl
        dt Begünstigter
        dd weg-li UG
        dt IBAN
        dd DE62 1001 7997 7808 6292 54
        dt Verwendungszweck
        dd SPENDE weg.li

.row
  .col-lg-6.text-center
    = link_to('https://github.com/sponsors/phoet/', target: '_blank', class: 'btn btn-success btn-lg btn-block')
      <span class="glyphicon glyphicon-piggy-bank"></span> Sponsoring per GitHub
    small Du kannst monatliche Beiträge festlegen, das hilft uns den Betrieb der Plattform sicherzustellen.

  .col-lg-6.text-center
    = link_to('https://opencollective.com/weg-li', target: '_blank', class: 'btn btn-success btn-lg btn-block')
      <span class="glyphicon glyphicon-piggy-bank"></span> Spenden per OpenCollective
    small Du kannst individuell festlegen wie Du spenden möchtest, auch einmalige Spenden sind möglich.

.spacer-large

.well.well-lg
  p
    |
      Vielen Dank für Dein Interesse an weg.li 😻 Wir freuen uns sehr darüber, dass wir alle gemeinsam einen Beitrag dazu leisten können,
      die Bürgersteige frei und die Radwege sicher zu machen 💪 Die weg.li Nutzer haben bereits über eine Millionen Anzeigen an Ordnungsämter verschickt,
      von solchen Zahlen hätten wir zum Start nicht zu träumen gewagt 🚀
  p
    |
      Dieser Erfolg bringt allerdings auch einige Dinge mit sich, denn natürlich steigen mit höherer Nutzung auch die Kosten für den Betrieb der Plattform,
      der Support-Aufwand und der Wunsch nach neuen Features benötigt viele Entwicklungsresourcen. Ohne die Hilfe von Freiwilligen und den Einsatz von Freizeit
      würde so ein Projekt schnell einen 6-Stelligen Kostenrahmen annehmen 💸
  p
    |
      Die Betriebskosten sind am einfachsten zu beziffern. Derzeit belaufen sie sich monatlich auf ca. 500 EUR:<br>
      ~ 100 EUR render.com (Web, Worker, Postgres, Redis, Cronjobs)<br>
      ~ 300 EUR GCloud (Storage, Vision-API)<br>
      ~ 100 EUR Cloudflare, Domainfactory (Domain-management, Image-Processing)<br>
  p
    |
      Wir brauchen eure Hilfe! Ob Geld-Spenden, die Recherche von Melde-Adressen der Ordnungsämter, Mund-zu-Mund-Propaganda via Social Media - egal, wir freuen uns über jede Art der Unterstützung 🥳

.spacer-large

.row
  .col-lg-6
    .well.well-chart.well-active
      <iframe src="https://github.com/sponsors/phoet/card" title="Sponsor phoet" style="border: 0; width: 100%; height: 300px;"></iframe>
  .col-lg-6
    .well.well-chart
      <script src="https://opencollective.com/weg-li/banner.js"></script>

app/views/home/map.html.slim
- set_title "Falschparker-Karte #{@district}"
- set_meta_description t('meta_description.map', district: @district)

.page-header
  h2.text-primary weg.li Falschparker-Karte #{@district}

.well
  | In den letzten #{@since} Tagen wurden in #{@district} insgesamt #{number_with_delimiter(@notices.size)} Anzeigen gegen Falschparker von #{number_with_delimiter(@active)} Benutzern erstattet.

- if signed_in?
  .row
    .col-lg-12
      = render("components/map/filter", notices: @notices, district: @district, display: @display, since: @since, init: @default_district.map_data)

  - if @notices.present?
    hr.spacer

    .row
      .col-lg-8
        h3 📈 Die häufigsten Vergehen
        ul.list-group
          - grouped = @notices.group_by(&:tbnr).sort_by {|_, group| group.size }.reverse
          - grouped.first(@limit).each do |key, group|
            li.list-group-item
              .badge.pull-right= number_with_delimiter(group.size)
              - charge = Charge.active.find_by(tbnr: key)
              = link_to charge.description, charge_path(key)

      .col-lg-4
        h3 📈 Die häufigsten Automarken
        ul.list-group
          - grouped = @notices.reject { |notice| notice.brand.blank? }.group_by(&:brand).sort_by {|_, group| group.size }.reverse
          - grouped.first(@limit).each do |key, group|
            li.list-group-item
              = render('components/vehicle_count', count: @notices.size, brand_count: group.size, brand: key)
- else
  .well
    = render('components/register', text: 'Diese Inhalte stehen nur unseren registrierten Benutzern zur Verfügung!')
    = image_tag "map.jpg", class: "img-responsive center-block img-rounded", alt: "Karte zur Falschparker App"

app/views/home/robots.text.erb
# See http://www.robotstxt.org/robotstxt.html for documentation on how to use the robots.txt file
#
<% if @disallow %>
User-agent: *
Disallow: /
<% else %>
User-agent: *
Disallow: /p/
Disallow: /rails/active_storage/blobs/redirect/

User-agent: GPTBot
Disallow: /

User-agent: CCbot
Disallow: /

User-agent: anthropic-ai
Disallow: /

User-agent: Claude-Web
Disallow: /

User-agent: Google-Extended
Disallow: /

User-agent: SeekportBot
Disallow: /

User-agent: barkrowler
Disallow: /

User-agent: SemrushBot
Disallow: /

User-agent: DotBot
Disallow: /

User-agent: Amazonbot
Disallow: /

User-agent: AhrefsBot
Disallow: /

User-agent: ImagesiftBot
Disallow: /

User-agent: Meta-ExternalAgent
Disallow: /

User-agent: Bytespider
Disallow: /
<% end %>

app/views/home/violation.html.slim
- set_title "Scheiße geparkt? Parkt nicht auf unseren Wegen!"
- set_meta_description "weg.li - Für sichere Radwege und freie Bürgersteige, besonders für Kinder!"

.page-header
  h2.text-primary=t('title')
  p.text-muted Für sichere Radwege und freie Bürgersteige, besonders für Kinder!

h3 Scheiße geparkt? Parkt nicht auf unseren Wegen!

p
  |
    Falschparken ist kein Kavaliersdelikt: Falschparker behindern Fußgänger, gefährden Radfahrer und sorgen dafür,
    dass Kinder, Alte und Menschen mit Behinderung sich nicht frei im öffentlichen Raum bewegen können.
    Darum ist es unsere Mission dem gesellschaftlich akzeptierten Falschparken in Deutschland etwas entgegen zu setzen.
    Wir bauen Druck auf, damit Ordnungsämter, Parkraummanagement und Polizei ihren hoheitlichen Aufgaben endlich nachgehen und angemessen tätig werden.

.spacer-large

.well
  = image_tag '404.jpg', width: '100%'

app/views/home/wegeheld.html.slim
.row
  .col-lg-3
    = image_tag('logo.png', class: "img-circle imprint-logo", alt: "weg.li logo")
    = image_tag('wegeheld.png', class: "img-circle imprint-logo", alt: "Wegeheld logo", style: "margin-left: -40px")
  .col-lg-9
    h1 weg.li + Wegeheld = 💙
    h3 Gemeinsam gegen Falschparker

.spacer-large

.well
  p Die Wegeheld Idee gibt es seit dem Jahr 2013 und zusammen haben wir seitdem viele Erfolge feiern können. Mit Sicherheit konnten wir unseren Beitrag zur breiten Unterstützung der StVO-Novelle leisten, die vor Kurzem im Bundestag verabschiedet wurde (und hoffentlich auch in naher Zukunft wirklich in Kraft tritt).
  p Die Wegeheld Apps für iOS und Android haben Fußgängern und Fahrradfahrern ein Werkzeug gegeben, um sich gegen das gesellschaftlich akzeptierte Falschparken zur Wehr zu setzen.
  p Inzwischen hat durch den Druck der vielen Verkehrsinitiativen wie z.B. <strong>#rollestattknolle</strong> und dem Wirken von Institutionen wie dem ADFC ein allgemeines Umdenken eingesetzt. Letztendlich hat auch der Gesetzgeber erkannt, dass es notwendig ist, die Strafen für das Falschparken zu verschärfen. <strong>#knollestattknöllchen</strong>
  p Neben der Wegeheld App sind inzwischen weitere Möglichkeiten entstanden, um Parkvergehen im Internet anzuzeigen. Auch viele Ordnungsämter bieten inzwischen Formulare im Internet dafür an. Zur deutschlandweiten Anzeige von Falschparkern gibt es seit August 2019 zudem unsere Webseite weg.li, die es noch einfacher macht, für sichere Radwege und freie Bürgersteige zu sorgen.
  p Viele Ideen von weg.li sind aus den Erfahrungen mit dem Umgang der Wegeheld-App entstanden und das Ziel von weg.li ist es, die Anzeige von Parkvergehen so einfach wie möglich zu gestalten. Das Wegeheld-Team ist begeistert von der einfachen Benutzbarkeit von weg.li. Genau so hatte sich das Team die Wegeheld-App immer gewünscht!
  p Anfang 2020 haben wir uns entschieden die Erfahrungen und die Reichweite von Wegeheld mit den Möglichkeiten von weg.li zu verbinden und unsere Kooperation offiziell bekannt geben:
  p Gemeinsam gegen Falschparker: <strong>weg.li + Wegeheld = 💙</strong>
  p Wir haben Wegeheld und weg.li verschmolzen und werden die Entwicklung bei weg.li weiterführen, um gemeinsam dafür zu kämpfen, unsere Innenstädte sicherer zu machen und uns den Raum vom Auto wieder zurückzuholen!

.spacer-large

.row
  .col-lg-12
    h3 🤪 Protest-Werkzeuge:

    ul.list-group
      li.list-group-item
        span.badge Tool
        | 🤡 Mit dem #{link_to 'weg.li Generator', generator_path} Spuckies und Flyer selber basteln.
      li.list-group-item
        span.badge Link
        | 💩 Auf die #{link_to '"Scheiße geparkt" Seite', violation_path} können besonders renitente Falschparker online verwiesen werden.

app/views/home/year.slim
- set_title "Falschparker-Übersicht #{@year}"

.page-header
  h2.text-primary weg.li das Jahr #{@year}

= cache("year_#{@year}_#{@limit}", expires_in: 12.hours) do
  = render("year_head", year: @year, users_count: yearly_statistics[:count], users_active: yearly_statistics[:active])

  hr.spacer

  ul.nav.nav-tabs.nav-panel
    - @years.each do |year|
      li(class="#{'active' if year == @year}") = link_to year, url_for(year: year)

  = render("year#{@year}", year: @year)
  = render('yearly_stats', statistics: yearly_statistics)